baseurl = "http://piotrkowalczuk.github.io"
title = "Piotr Kowalczuk Blog"
theme = "ghostwriter"
languageCode = "pl"
copyright = "Piotr Kowalczuk"
googleAnalytics = "UA-50599199-4"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true

[Author]
    name = "Piotr Kowalczuk"
    profile = "https://piotrkowalczuk.github.io"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Clear is better than clever"
    description = "Golang Development"
    github = "https://github.com/piotrkowalczuk"
    linkedin = "https://linkedin.com/in/piotr-kowalczuk-8a870480/"
    stackoverflow = "http://stackoverflow.com/users/XXX/YYY"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3